<?php

return [
    'app.css' => [
        'application.src.css',
    ],
    'app.js' => [
//        '/api/script/export/i18n.js',
        'application/core.src.js',
        'application/object.src.js',
        'application/interactive_object.src.js',
        'application/window.src.js',
        'application/filter_window.src.js',
        'application/data_table.src.js',
        'application/side_menu.src.js',
        'application/bootstrap.src.js',
    ],
    'annotation.js' => [
        'openseadragon.src.js',
        'jsoneditor.src.js',
        'seanote/check.src.js',
        'seanote/init.src.js',
        'seanote/core.src.js',
        'seanote/object.src.js',
        'seanote/interactive_object.src.js',
        'seanote/window.src.js',
        'seanote/canvas_object.src.js',
        'seanote/canvas_segment.src.js',
        'seanote/canvas_segment_group.src.js',
        'seanote/canvas_selection.src.js',
        'seanote/canvas.src.js',
        'seanote/annotator.src.js',
        'seanote/entity_editor.src.js',
        'seanote/menu.src.js',
        'seanote/menu_item.src.js',
        'seanote/toolbar.src.js',
        'seanote/button.src.js',
        'seanote/control_bar.src.js',
        'seanote/navigator.src.js',
        'seanote/filmstrip.src.js',
        'seanote/sidebar.src.js',
        'seanote/browser.src.js',
        'seanote/modal.src.js',
        'seanote/validator.src.js',
        'seanote/viewer.src.js',
    ],
	'core.css' => [
        'fonts.src.css',
        'jquery.ui.src.css',
        'semantic.src.css',
        'semantic.calendar.src.css',
        'semantic.range.src.css',
    ],
	'core.js' => [
	    'date_format.src.js',
        'mousetrap.src.js',
        'jquery.src.js',
        'jquery.throttle_debounce.src.js',
        'jquery.serialize_object.src.js',
        'jquery.scrollto.src.js',
        'jquery.ui.src.js',
        'semantic.src.js',
        'semantic.calendar.src.js',
        'semantic.range.src.js',
    ],
    'datatables.css' => [
        'datatables/semantic.src.css',
        'datatables/fixed_header.semantic.src.css',
        'datatables/buttons.semantic.src.css',
        'datatables/key_table.semantic.src.css',
        'datatables/select.semantic.src.css',
    ],
    'datatables.js' => [
        'jszip.src.js',
        'datatables/core.src.js',
        'datatables/semantic.src.js',
        'datatables/fixed_header.src.js',
        'datatables/buttons.src.js',
        'datatables/buttons.html5.src.js',
        'datatables/buttons.print.src.js',
        'datatables/buttons.semantic.src.js',
        'datatables/key_table.src.js',
        'datatables/select.src.js',
    ],
    'map.css' => [
        'ol.debug.src.css',
        'webmap.src.css',
    ],
    'map.js' => [
        'ol.debug.src.js',
        'tiny_color.src.js',
        'tiny_gradient.src.js',
        'webmap.src.js',
    ],
    'sparql.css' => [
        'codemirror.src.css',
        'datatables/semantic.src.css',
        'yasqe.src.css',
        'yasr.src.css',
    ],
    'sparql.js' => [
        'codemirror.src.js',
        'datatables/core.src.js',
        'datatables/semantic.src.js',
        'yasqe.src.js',
        'yasr.src.js',
        'application/data.src.js',
    ],
    'prism.css' => [
        'prism.src.css',
    ],
    'prism.js' => [
        'prism.src.js',
    ],
    'visualization.css' => [
        'taucharts.src.css',
    ],
    'visualization.js' => [
        'd3.src.js',
        'taucharts.src.js',
        'taucharts.color_brewer.src.js',
    ]
];

// -- End of file
