<?php

$entityTypes = [
    'dhc:Concept',
    'dhc:Token',
    'oa:Motivation',
    'sc:ViewingDirection',
    'sc:ViewingHint',
    'dhc:Language',
    'dhc:Style',
    'dhc:List',
    'dhc:ConceptScheme',
    'dhc:Manifest',
    'dhc:ManifestCollection',
    'dhc:Canvas',
    'dhc:CanvasSequence',
    'dhc:CanvasRange',
    'dhc:CanvasPoint',
    'dhc:CanvasSegment',
    'dhc:CanvasSegmentGroup',
    'dhc:CanvasSegmentLink',
    'dhc:Annotation',
    'dhc:Image',
    'dhc:Transcription',
    'dhc:Tag',
    'dhc:SemanticTag',
    'dhc:Category',
    'dhc:Comment',
    'grz:Contract',
    'grz:Person',
    'grz:Event',
    'grz:Sestriere',
    'grz:Parish',
    'grz:CurrencyUnit',
    'grz:ContractMention',
    'grz:PersonMention',
    'grz:EventMention',
    'grz:FinancialConditionMention',
    'grz:HostingConditionMention',
    'grz:ProfessionMention',
    'grz:NumberMention',
];

// -- End of file
